from django.urls import path
from .views import (
    SyncStatusView,
    AdminAuditLogsListView,
    BlacklistDownloadView,
    SubmitReportView,
    CheckNumberView,
    RegisterView,
    EmailLoginView,
    GoogleLoginView,
    UserProfileView,
    AdminStatsView,
    AdminModerateView,
    AdminBlacklistManagerView,
    AdminBlacklistDetailView,
    AdminUsersListView,
    AdminReportsListView,
    AdminPurgeJunkView,
    SubmitSafeReportView,
    ConsensusStatusView,
    AdminConsensusAuditView,
    AdminSafeReportsListView,
    HealthCheckView,
)

urlpatterns = [
    path('health/', HealthCheckView.as_view(), name='health-check'),
    path('sync/status/', SyncStatusView.as_view(), name='sync-status'),
    path('blacklist/', BlacklistDownloadView.as_view(), name='blacklist-download'),
    path('reports/', SubmitReportView.as_view(), name='submit-report'),
    path('reports/safe/', SubmitSafeReportView.as_view(), name='submit-safe-report'),
    path('check/<str:phone_hash>/', CheckNumberView.as_view(), name='check-number'),
    path('consensus/<str:phone_hash>/', ConsensusStatusView.as_view(), name='consensus-status'),
    path('auth/register/', RegisterView.as_view(), name='auth-register'),
    path('auth/login/', EmailLoginView.as_view(), name='auth-login'),
    path('auth/google/', GoogleLoginView.as_view(), name='auth-google'),
    path('auth/me/', UserProfileView.as_view(), name='auth-me'),
    path('admin/stats/', AdminStatsView.as_view(), name='admin-stats'),
    path('admin/moderate/', AdminModerateView.as_view(), name='admin-moderate'),
    path('admin/blacklist/', AdminBlacklistManagerView.as_view(), name='admin-blacklist'),
    path('admin/blacklist/<str:phone_hash>/', AdminBlacklistDetailView.as_view(), name='admin-blacklist-detail'),
    path('admin/users/', AdminUsersListView.as_view(), name='admin-users'),
    path('admin/reports/', AdminReportsListView.as_view(), name='admin-reports'),
    path('admin/reports/<str:report_id>/', AdminReportsListView.as_view(), name='admin-reports-detail'),
    path('admin/safe-reports/', AdminSafeReportsListView.as_view(), name='admin-safe-reports'),
    path('admin/consensus-audit/', AdminConsensusAuditView.as_view(), name='admin-consensus-audit'),
    path('admin/purge/', AdminPurgeJunkView.as_view(), name='admin-purge'),
    path('admin/audit-logs/', AdminAuditLogsListView.as_view(), name='admin-audit-logs'),
]

