# Generated by Django 4.2.11 on 2026-09-17 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shield_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklistednumber",
            name="consensus_score",
            field=models.FloatField(
                default=0.0,
                help_text="Score de consensualité légitime calculé de 0.0 (100% spam) à 1.0 (100% légitime)",
            ),
        ),
        migrations.AddField(
            model_name="blacklistednumber",
            name="safe_reports_count",
            field=models.IntegerField(
                default=0,
                help_text="Nombre total d'avis favorables ou contestations de faux positif soumis",
            ),
        ),
        migrations.AddField(
            model_name="blacklistednumber",
            name="whitelist_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Origine de la décision de blanchiment : 'auto_consensus', 'manual_admin', etc.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blacklistednumber",
            name="is_whitelisted",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le numéro a été blanchi / approuvé (faux positif résolu)",
            ),
        ),
        migrations.CreateModel(
            name="SafeReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("service", "Service légitime / Entreprise certifiée"),
                            ("personal", "Contact personnel / Famille / Ami"),
                            ("delivery", "Service de livraison / Transport"),
                            ("medical", "Santé / Cabinet médical / Urgence"),
                            ("mistake", "Erreur de signalement préalable"),
                            ("other", "Autre usage légitime"),
                        ],
                        default="service",
                        max_length=30,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safe_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis de légitimité",
                "verbose_name_plural": "Avis de légitimité (Consensualité)",
                "ordering": ["-created_at"],
            },
        ),
    ]
