# Generated by Django 4.2.11 on 2026-09-17 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shield_api", "0002_blacklistednumber_consensus_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("APPROVE_BLOCK", "Approuver et Bloquer"),
                            ("WHITELIST_UNBLOCK", "Débloquer et Blanchir"),
                            ("MANUAL_ADD", "Ajout Manuel"),
                            ("DELETE_NUMBER", "Suppression de la Liste Noire"),
                            ("DELETE_REPORT", "Suppression de Signalement"),
                            ("PURGE_DATABASE", "Purge de la Base"),
                        ],
                        max_length=40,
                    ),
                ),
                ("details", models.TextField(blank=True, default="")),
                (
                    "target_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("source", models.CharField(default="MOBILE_ADMIN", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'Audit",
                "verbose_name_plural": "Journaux d'Audit",
                "ordering": ["-created_at"],
            },
        ),
    ]
