# Generated by Django 4.2.11 on 2026-09-18 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shield_api", "0003_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklistednumber",
            name="phone_hash",
            field=models.CharField(
                db_index=True,
                help_text="Empreinte SHA-256 anonymisée du numéro de téléphone",
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="L'empreinte phone_hash doit être un hash SHA-256 hexadécimal valide de 64 caractères.",
                        regex="^[a-fA-F0-9]{64}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="safereport",
            name="phone_hash",
            field=models.CharField(
                db_index=True,
                help_text="Empreinte SHA-256 du numéro contesté",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="L'empreinte phone_hash doit être un hash SHA-256 hexadécimal valide de 64 caractères.",
                        regex="^[a-fA-F0-9]{64}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="spamreport",
            name="phone_hash",
            field=models.CharField(
                db_index=True,
                help_text="Empreinte SHA-256 du numéro signalé",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="L'empreinte phone_hash doit être un hash SHA-256 hexadécimal valide de 64 caractères.",
                        regex="^[a-fA-F0-9]{64}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "created_at"], name="idx_audit_action_created"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_hash", "created_at"], name="idx_audit_hash_created"
            ),
        ),
        migrations.AddIndex(
            model_name="blacklistednumber",
            index=models.Index(
                fields=["is_blocked", "is_whitelisted", "risk_score"],
                name="idx_bl_active_filter",
            ),
        ),
        migrations.AddIndex(
            model_name="blacklistednumber",
            index=models.Index(fields=["updated_at"], name="idx_bl_updated_at"),
        ),
        migrations.AddIndex(
            model_name="blacklistednumber",
            index=models.Index(
                fields=["phone_hash", "is_blocked"], name="idx_bl_hash_blocked"
            ),
        ),
        migrations.AddIndex(
            model_name="safereport",
            index=models.Index(
                fields=["phone_hash", "created_at"], name="idx_safe_hash_created"
            ),
        ),
        migrations.AddIndex(
            model_name="safereport",
            index=models.Index(
                fields=["reason", "created_at"], name="idx_safe_reason_created"
            ),
        ),
        migrations.AddIndex(
            model_name="spamreport",
            index=models.Index(
                fields=["phone_hash", "created_at"], name="idx_spam_hash_created"
            ),
        ),
        migrations.AddIndex(
            model_name="spamreport",
            index=models.Index(
                fields=["category", "created_at"], name="idx_spam_cat_created"
            ),
        ),
    ]
