# Generated by Django 4.2.11 on 2026-09-30 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shield_api", "0004_alter_blacklistednumber_phone_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("CA", "Canada"), ("US", "États-Unis")],
                        db_index=True,
                        default="CA",
                        help_text="Pays de résidence de l'utilisateur (CA: Canada, US: États-Unis)",
                        max_length=2,
                    ),
                ),
                (
                    "province_or_state",
                    models.CharField(
                        db_index=True,
                        default="QC",
                        help_text="Province/Territoire canadien (ex: QC, ON) ou État américain (ex: NY, CA)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Régional Utilisateur",
                "verbose_name_plural": "Profils Régionaux Utilisateurs",
                "indexes": [
                    models.Index(
                        fields=["country", "province_or_state"],
                        name="idx_profile_region",
                    )
                ],
            },
        ),
    ]
